name: Sync to Mirror Repository

on:
  push:
    branches:
      - main # Dispara el workflow al realizar cambios en la rama principal.
  schedule:
    - cron: "0 0 * * *" # También se ejecutará automáticamente cada día a medianoche.
  workflow_dispatch: # Permite ejecutar el workflow manualmente.

jobs:
 sync:
  runs-on: ubuntu-latest
  env:
    ACCESS_TOKEN: ${{ secrets.PERSONAL_MADISSUES_ACCESS_TOKEN }}
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add mirror remote
      run: |
        git remote add mirror https://antonioap101:${ACCESS_TOKEN}@github.com/antonioap101/madissues-frontend.git

    - name: Verify remote configuration
      run: git remote -v

    - name: Push to mirror
      run: |
        git push mirror --all --force
        git push mirror --tags --force


          
