name: Sync to Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add mirror remote
        run: |
          git remote add mirror https://antonioap101:${{ secrets.PERSONAL_MADISSUES_ACCESS_TOKEN }}@github.com/antonioap101/madissues-frontend.git

      - name: Verify remote configuration
        run: git remote -v

      - name: Push to mirror
        run: |
          git push mirror --all --force
          git push mirror --tags --force
